[system]
# Name
system_name = "40BuOH-CG-7"
# Files
topology_file_path = "configs/butanol-data/40BuOH/first_frame.pdb"
trajectory_file_path = "configs/butanol-data/40BuOH/40Bu200step.xtc"
rdf_file_path = "configs/butanol-data/40BuOH/rdf40bu.txt"
# Simulation
temperature = 300             # Temperature [K]
max_displacement = 8.50       # Maximum atomic displacement [Å]
target_acceptance_ratio = 0.5 # Monte Carlo acceptance ratio target
concentration = 40.0          # System concentration
