[system]
# Name
system_name = "10CH3OH-CG-7"
# Files
topology_file_path = "configs/methanol-data/10CH3OH/10CH3OH-CG.pdb"
trajectory_file_path = "configs/methanol-data/10CH3OH/10CH3OH-CG-200.xtc"
rdf_file_path = "configs/methanol-data/10CH3OH/10CH3OH-CG.rdf"
# Simulation
temperature = 298.15          # Temperature [K]
max_displacement = 8.50       # Maximum atomic displacement [Å]
target_acceptance_ratio = 0.5 # Monte Carlo acceptance ratio target
concentration = 10.0          # System concentration
