# Global scaling factor (1.0 = no scaling)
scaling = 1.0

# G2 symmetry functions (radial symmetry)
# Format: eta (Å^-2), rcutoff (Å), rshift (Å)
G2 = [
    # eta  rcutoff  rshift
    # G2(0) - local density
    [0.000, 15.0, 0.00],
    # G2 wide - Repulsion
    [0.000, 3.60, 0.00],
    # G2 wide - Long Distance 3.0
    [0.050, 15.0, 0.00],
    [0.050, 15.0, 3.00],
    [0.050, 15.0, 6.00],
    # G2 brute step 1.0
    [0.500, 15.0, 3.00],
    [0.500, 15.0, 4.00],
    [0.500, 15.0, 5.00],
    [0.500, 15.0, 6.00],
    # G2 step 0.25
    [10.450, 15.0, 3.00],
    [10.450, 15.0, 3.25],
    [10.450, 15.0, 3.50],
    [10.450, 15.0, 3.75],
    [10.450, 15.0, 4.00],
    [10.450, 15.0, 4.25],
    [10.450, 15.0, 4.50],
    [10.450, 15.0, 4.75],
    [10.450, 15.0, 5.00],
    [10.450, 15.0, 5.25],
    [10.450, 15.0, 5.50],
    [10.450, 15.0, 5.75],
    [10.450, 15.0, 6.00],
]

# G3 symmetry functions (narrow angular symmetry)
# Format: eta (Å^-2), lambda (+1/-1), zeta, rcutoff (Å), rshift (Å)
# G3 = [
#     # eta  lambda  zeta  rcutoff  rshift
#     [0.001,  1.0, 1.0, 5.0, 0.0],
#     [0.001, -1.0, 1.0, 5.0, 0.0],
# ]

# G9 symmetry functions (wide angular symmetry)
# Format: eta (Å^-2), lambda (+1/-1), zeta, rcutoff (Å), rshift (Å)
# G9 = [
#     # eta  lambda  zeta  rcutoff  rshift
#     [0.001,  1.0, 1.0, 5.0, 0.0],
#     [0.001, -1.0, 1.0, 5.0, 0.0],
# ]
