[system]
# Name
system_name = "70CH3OH-CG-8"
# Files
topology_file_path = "configs/methanol-data/70CH3OH/70CH3OH-CG.pdb"
trajectory_file_path = "configs/methanol-data/70CH3OH/70CH3OH-CG-200.xtc"
rdf_file_path = "configs/methanol-data/70CH3OH/70CH3OH-CG.rdf"
# Simulation
temperature = 298.15          # Temperature [K]
max_displacement = 1.70       # Maximum atomic displacement [Å]
target_acceptance_ratio = 0.5 # Monte Carlo acceptance ratio target
concentration = 70.0          # System concentration
