[system]
# Name
system_name = "60CH3OH-CG-3"
# Files
topology_file_path = "configs/methanol-data/60CH3OH/60CH3OH-CG.pdb"
trajectory_file_path = "configs/methanol-data/60CH3OH/60CH3OH-CG-200.xtc"
rdf_file_path = "configs/methanol-data/60CH3OH/60CH3OH-CG.rdf"
# Simulation
temperature = 298.15          # Temperature [K]
max_displacement = 1.80       # Maximum atomic displacement [Å]
target_acceptance_ratio = 0.5 # Monte Carlo acceptance ratio target
concentration = 60.0          # System concentration
