[system]
# Name
system_name = "10BuOH-CG-6"
# Files
topology_file_path = "configs/butanol-data/10BuOH/first_frame.pdb"
trajectory_file_path = "configs/butanol-data/10BuOH/10Bu200step.xtc"
rdf_file_path = "configs/butanol-data/10BuOH/rdf10bu.txt"
# Simulation
temperature = 300             # Temperature [K]
max_displacement = 8.50       # Maximum atomic displacement [Å]
target_acceptance_ratio = 0.5 # Monte Carlo acceptance ratio target
concentration = 10.0          # System concentration
